apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-petclinic-24
  name: spring-petclinic-24
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-petclinic-24
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-petclinic-24
    spec:
      containers:
      - image: 866421524471.dkr.ecr.us-east-2.amazonaws.com/spring-petclinic:24
        imagePullPolicy: IfNotPresent
        name: spring-petclinic
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
