apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-flask
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/conditions.flask-svc-alb-blue: '[{"Field":"query-string","QueryStringConfig":{"Values":[{"Key":"name","Value":"blue"}]}}]'
    # alb.ingress.kubernetes.io/conditions.flask-svc-alb-green: '[{"Field":"query-string","QueryStringConfig":{"Values":[{"Key":"name","Value":"green"}]}}]'
spec:
  rules:
    - host: prod.devopsmaster.cloud
      http:
        paths:
          - path: /
            backend:
              serviceName: BLUE_NAME
              servicePort: 80
    - host: green.devopsmaster.cloud
      http:
        paths:
          - path: /
            backend:
              serviceName: hello-flask-GREEN
              servicePort: 80