apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-flask-NUMBER
    role: green
  name: hello-flask-NUMBER
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello-flask-NUMBER

